"""Products table and relationship

Revision ID: d32d432cbc25
Revises: 77be6009b70d
Create Date: 2025-05-23 09:51:21.963669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32d432cbc25'
down_revision: Union[str, None] = '77be6009b70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('categories', sa.Column('createdAt', sa.DateTime(), nullable=True))
    # op.alter_column('categories', 'name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('categories', 'name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    op.drop_column('categories', 'createdAt')
    op.drop_table('products')
    # ### end Alembic commands ###
